version: '2'
services: 
    rabbitmq:
        image: "rabbitmq:3.6-management"
        ports:
            - "15672:15672"
    consumer:
        build: ./consumer
        volumes: 
            - .:/consumer      
    producer:
        build: ./producer
        volumes: 
            - .:/producer
        ports:
            - "80:80"
       